MAPS_DATA = {
    "Ground Zero": {
        "waves": {
            0: ("slime",),
            1: ("slime", "ghost"),
            2: ("slime", "ghost", "slime"),
            3: ("fast_slime", "fast_slime", "slime", "slime", "ghost", "ghost"),
            4: (
                "fast_slime",
                "fast_slime",
                "fast_slime",
                "slime",
                "slime",
                "ghost",
                "ghost",
            ),
            5: (
                "fast_slime",
                "fast_slime",
                "fast_slime",
                "fast_slime",
                "fast_slime",
                "slime",
                "slime",
                "slime",
                "slime",
                "ghost",
                "ghost",
                "ghost",
            ),
            6: (
                "fast_slime",
                "fast_slime",
                "fast_slime",
                "slime",
                "slime",
                "slime",
                "slime",
                "ghost",
                "ghost",
                "ghost",
                "ghost",
                "ghost",
                "ghost",
            ),
            7: (
                "fast_slime",
                "fast_slime",
                "fast_slime",
                "fast_slime",
                "fast_slime",
                "fast_slime",
                "slime",
                "slime",
                "ghost",
                "ghost",
                "ghost",
                "ghost",
                "ghost",
                "ghost",
            ),
            8: (
                "slime",
                "slime",
                "slime",
                "slime",
                "fast_slime",
                "fast_slime",
                "fast_slime",
                "fast_slime",
                "ghost",
                "ghost",
                "ghost",
                "ghost",
                "tank_slime",
            ),
        },
        "initial_balance": 300,
        "health": 50,
    },
    "Frontier": {
        "waves": {
            0: ("slime", "slime"),
            1: ("slime", "ghost", "slime"),
            2: ("slime", "fast_slime", "ghost", "slime"),
            3: (
                "fast_slime",
                "fast_slime",
                "slime",
                "slime",
                "ghost",
                "ghost",
            ),
            4: (
                "fast_slime",
                "fast_slime",
                "fast_slime",
                "slime",
                "slime",
                "slime",
                "ghost",
                "ghost",
                "ghost",
            ),
            5: (
                "fast_slime",
                "fast_slime",
                "fast_slime",
                "fast_slime",
                "fast_slime",
                "slime",
                "slime",
                "slime",
                "ghost",
                "ghost",
                "ghost",
                "ghost",
            ),
            6: (
                "fast_slime",
                "fast_slime",
                "fast_slime",
                "fast_slime",
                "fast_slime",
                "slime",
                "slime",
                "slime",
                "slime",
                "ghost",
                "ghost",
                "ghost",
                "ghost",
                "tank_slime",
            ),
            7: (
                "fast_slime",
                "fast_slime",
                "fast_slime",
                "fast_slime",
                "fast_slime",
                "fast_slime",
                "slime",
                "slime",
                "slime",
                "ghost",
                "ghost",
                "ghost",
                "ghost",
                "ghost",
                "tank_slime",
            ),
            8: (
                "fast_slime",
                "fast_slime",
                "fast_slime",
                "fast_slime",
                "fast_slime",
                "fast_slime",
                "slime",
                "slime",
                "slime",
                "slime",
                "ghost",
                "ghost",
                "ghost",
                "ghost",
                "ghost",
                "tank_slime",
                "tank_slime",
            ),
        },
        "initial_balance": 325,
        "health": 50,
    },
}
