ALL_MAP_MUSIC = ["Heroic Demise", "Soliloquy", "The Fall of Arcana"]

MAPS_DATA = {
    "Ground Zero": {
        "waves": {
            0: ("slime", "slime"),
            1: ("slime", "ghost", "slime"),
            2: ("slime", "fast_slime", "ghost", "crab"),
            3: ("fast_slime", "fast_slime", "slime", "ghost", "crab"),
            4: ("slime", "slime", "fast_slime", "ghost", "crab", "bat"),
            5: ("fast_slime", "fast_slime", "ghost", "ghost", "crab", "bat"),
            6: ("slime", "fast_slime", "ghost", "crab", "crab", "bat", "bat"),
            7: (
                "fast_slime",
                "fast_slime",
                "ghost",
                "ghost",
                "crab",
                "bat",
                "tank_slime",
            ),
            8: (
                "slime",
                "fast_slime",
                "fast_slime",
                "ghost",
                "ghost",
                "crab",
                "bat",
                "armored_crab",
            ),
        },
        "initial_balance": 260,
        "health": 25,
        "music": ALL_MAP_MUSIC,
    },
    "Frontier": {
        "waves": {
            0: ("slime", "slime", "ghost"),
            1: ("slime", "fast_slime", "ghost", "crab"),
            2: ("fast_slime", "fast_slime", "ghost", "crab", "bat"),
            3: ("slime", "fast_slime", "ghost", "ghost", "crab", "bat"),
            4: ("fast_slime", "fast_slime", "crab", "crab", "bat", "bat"),
            5: (
                "slime",
                "ghost",
                "ghost",
                "crab",
                "bat",
                "bat",
                "tank_slime",
            ),
            6: (
                "fast_slime",
                "fast_slime",
                "ghost",
                "crab",
                "crab",
                "bat",
                "bat",
            ),
            7: (
                "fast_slime",
                "ghost",
                "ghost",
                "crab",
                "crab",
                "bat",
                "tank_slime",
            ),
            8: (
                "fast_slime",
                "fast_slime",
                "ghost",
                "ghost",
                "crab",
                "crab",
                "bat",
                "armored_crab",
            ),
        },
        "initial_balance": 300,
        "health": 25,
        "music": ALL_MAP_MUSIC,
    },
    "Molten Lands": {
        "waves": {
            0: (
                "slime",
                "fast_slime",
                "ghost",
                "crab",
            ),
            1: (
                "fast_slime",
                "fast_slime",
                "ghost",
                "crab",
                "bat",
            ),
            2: (
                "slime",
                "fast_slime",
                "ghost",
                "ghost",
                "crab",
                "bat",
                "lava_slime",
            ),
            3: (
                "fast_slime",
                "fast_slime",
                "ghost",
                "crab",
                "crab",
                "bat",
                "lava_slime",
            ),
            4: (
                "fast_slime",
                "fast_slime",
                "ghost",
                "ghost",
                "crab",
                "bat",
                "bat",
                "lava_slime",
            ),
            5: (
                "fast_slime",
                "fast_slime",
                "fast_slime",
                "ghost",
                "ghost",
                "crab",
                "crab",
                "bat",
                "lava_slime",
            ),
            6: (
                "fast_slime",
                "fast_slime",
                "ghost",
                "ghost",
                "crab",
                "crab",
                "bat",
                "lava_slime",
                "lava_slime",
            ),
            7: (
                "fast_slime",
                "fast_slime",
                "ghost",
                "ghost",
                "crab",
                "crab",
                "bat",
                "bat",
                "lava_slime",
                "tank_slime",
            ),
            8: (
                "fast_slime",
                "fast_slime",
                "ghost",
                "ghost",
                "ghost",
                "crab",
                "crab",
                "bat",
                "lava_slime",
                "lava_slime",
                "armored_crab",
            ),
            9: (
                "fast_slime",
                "fast_slime",
                "fast_slime",
                "ghost",
                "ghost",
                "crab",
                "crab",
                "bat",
                "bat",
                "lava_slime",
                "lava_slime",
                "tank_slime",
                "armored_crab",
            ),
        },
        "initial_balance": 350,
        "health": 25,
        "music": ALL_MAP_MUSIC,
    },
}
